import chalk from "chalk";
import { getUserInput } from "./user.js";
import { checkFlag } from "./flag.js";
import { score, match } from "./checkAnswer.js";
console.log(chalk.bgYellow(`\n\t\t\t\t***WELCOME TO NUMBER GUESSING GAME***\n`));
console.log(chalk.yellow(`You will have 5 tries, there will be new number generated by system every time and score out of 5 will be generated at end\n`));
let flag = true;
export let userInput;
while (flag) {
    for (let i = 0; i < 5; i++) {
        userInput = await getUserInput();
        match();
    }
    console.log(chalk.bgWhite(`Your score is ${score}/5\n`));
    flag = await checkFlag();
}
